[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-resty/resty"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"
